zip_keys:
  - [python, numpy, python_impl, is_python_min]


python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313*

python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython

numpy:
  - 1.26
  - 1.26
  - 1.26
  - 1.26
  - 2.1

is_python_min:
  - false
  - false
  - false
  - false
  - false
